services:
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    image: mongo
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

  mongoexpress:
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    image: mongo-express
    ports:
      - 8081:8081
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080

volumes:
  mongo-data:
